# Generated by Django 3.2.4 on 2023-01-03 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_tag_projects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='projects',
        ),
    ]
